REM lab42.sql

create table team (
	TNO		NUMBER (2) CONSTRAINT PK_TEAM PRIMARY KEY,
	TNA		CHAR (20),
	GRP	 	CHAR (1) 
);

create table game (
	GNO		NUMBER CONSTRAINT PK_GAME PRIMARY KEY,
	GAME_DATE	DATE,
	TEAM_1		NUMBER (2) CONSTRAINT REF_GAME_1 REFERENCES TEAM(TNO),
	TEAM_1_GOALS	NUMBER (2),
	TEAM_2		NUMBER (2) CONSTRAINT REF_GAME_2 REFERENCES TEAM(TNO),
	TEAM_2_GOALS	NUMBER (2),
	ROUND		CHAR (7) 
);

